### ISSUE TITLE
Exception in version regex when trying to run an update

### ISSUE THREAD

**Issue by kitation** [RobinKnipe/accessibility-statement-generator#9]
Hi

I'm part of the Accessibility and Digital Inclusion team and I'm testing this out. I'm having an issue when trying to update this statement, either by the edit answers or regenerate statement options. I have attached my json file.

`UnhandledPromiseRejectionWarning: SyntaxError: Invalid regular expression: /-v(?<version>\d+)\.\w+/: Invalid group
    at glob.map.p (/Users/chadgowler/Documents/GitHub/accessibility-statement-generator/plopfile.js:326:21)`

[Refugee Integration Loan-2020-10-09.json.zip](https://github.com/RobinKnipe/accessibility-statement-generator/files/5353547/Refugee.Integration.Loan-2020-10-09.json.zip)

**Comment by RobinKnipe** [comment]
Hi @kitation - thanks for getting involved! This failure is part of a defence to stop accidentally overwriting files. This works fine locally for me, the only thing I can think of is something to do with your Node.js version perhaps? It's possible the "named group" syntax here is new. I'm on node v12.14.1, how about you? You can find the version by running: `node -v`

**Comment by kitation** [comment]
Ah good call, I was using v8.12. I tried it in v14.2 but I get an issue when it tried to generate the HTML file `[ERROR]  The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of VFile`

**Comment by kitation** [comment]
Tried in v12 and it's all good. Might be worth popping a .nvmrc file in or putting the node version in the readme

**Comment by RobinKnipe** [comment]
That's great. Thanks for the feedback, I'll make some improvements...

**Comment by RobinKnipe** [comment]
From my recollection, the `VFile` should be transformed into a `string` (using its `tiString` method), I'm not sure why that would suddenly stop happening in v14 of Node, but I'm pretty sure I can just explicitly call the method and fix that.

**Comment by RobinKnipe** [comment]
The `VFile` issue in node 14 has been fixed in PR #11
